esphome:
  name: bed
  friendly_name: "Bed"

esp8266:
  board: nodemcuv2
  restore_from_flash: true

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: NONE
  ap:
    ssid: "Bed AP"
    password: "12345678"

logger:
  level: INFO
api:
ota:
  - platform: esphome
captive_portal:
web_server:
improv_serial:
debug:

# ========== SENSORS ==========

sensor:
  - platform: wifi_signal
    name: "WiFi Signal (dBm)"
    id: wifi_signal_db
    update_interval: 60s
    entity_category: "diagnostic"

  - platform: uptime
    name: "Uptime"
    unit_of_measurement: "s"
    entity_category: "diagnostic"

  - platform: debug
    free:
      name: "Heap Free"

text_sensor:
  - platform: wifi_info
    ssid:
      name: "Connected SSID"
      icon: "mdi:wifi"
      entity_category: "diagnostic"

# ========== LIGHTS ==========
light:
  # 1. MASTER PHYSICAL LIGHT
  - platform: neopixelbus
    variant: ws2812x
    type: GRB
    pin: GPIO02
    num_leds: 175
    id: strip_light
    name: "Light"
    restore_mode: RESTORE_DEFAULT_OFF
    default_transition_length: 0s
    effects:
      - addressable_twinkle:
      - random
      - addressable_rainbow
      - addressable_color_wipe
          

  # 2. LOGICAL PARTITIONS
  - platform: partition
    name: "Bottom"
    id: light_bot
    segments: 
      - id: strip_light
        from: 0
        to: 53
        
  - platform: partition
    name: "Middle"
    id: light_mid
    segments: 
      - id: strip_light
        from: 54
        to: 144
        
  - platform: partition
    name: "Top"
    id: light_top
    segments: 
      - id: strip_light
        from: 145
        to: 174