esphome:
  name: floorlamp_2
  friendly_name: "Floorlamp 2"

esp32:
  board: esp32-c3-devkitm-1
  framework: 
    type: esp-idf

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: NONE
  ap:
    ssid: "Floorlamp 2 AP"
    password: "12345678"

logger:
  level: INFO
api:
ota:
  - platform: esphome
captive_portal:
web_server:
improv_serial:
debug:

# ========== SENSORS ==========
sensor:
  - platform: wifi_signal
    name: "WiFi Signal (dBm)"
    id: wifi_signal_db
    update_interval: 60s
    entity_category: "diagnostic"

  - platform: uptime
    name: "Uptime"
    unit_of_measurement: "s"
    entity_category: "diagnostic"
    
  - platform: debug
    free:
      name: "Available Heap"

text_sensor:
  - platform: wifi_info
    ssid:
      name: "Connected SSID"
      icon: "mdi:wifi"
      entity_category: "diagnostic"

# ========== LIGHTS ==========
light:
  # 1. MASTER PHYSICAL LIGHT
  - platform: esp32_rmt_led_strip
    rgb_order: GRB
    chipset: SK6812
    is_rgbw: true
    pin: GPIO02
    num_leds: 88
    id: strip_light
    name: "Light"
    restore_mode: RESTORE_DEFAULT_OFF
    effects:
      - addressable_twinkle:
      - random
      - addressable_rainbow
      - addressable_color_wipe
          

  # 2. LOGICAL PARTITIONS
  - platform: partition
    name: "Bottom"
    id: light_bot
    segments: 
      - id: strip_light
        from: 0
        to: 28
        
  - platform: partition
    name: "Middle"
    id: light_mid
    segments: 
      - id: strip_light
        from: 29
        to: 57
        
  - platform: partition
    name: "Top"
    id: light_top
    segments: 
      - id: strip_light
        from: 58
        to: 87