esphome:
  name: voice_assistant_1
  friendly_name: "Voice Assistant 1"
  platformio_options:
    board_build.flash_mode: dio
  on_boot:
    - priority: -100
      then:
        - light.turn_on:
            id: light_id
            blue: 100%
            brightness: 60%
            effect: fast pulse
        - delay: 2s
        - light.turn_off: light_id

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_ESP32S3_DEFAULT_CPU_FREQ_240: "y"
      CONFIG_ESP32S3_DATA_CACHE_64KB: "y"
      CONFIG_ESP32S3_DATA_CACHE_LINE_64B: "y"
      CONFIG_AUDIO_BOARD_CUSTOM: "y"
      # Optimized WiFi settings for media streaming
      CONFIG_ESP32_WIFI_STATIC_RX_BUFFER_NUM: "16"
      CONFIG_ESP32_WIFI_DYNAMIC_RX_BUFFER_NUM: "64"
      CONFIG_TCP_SND_BUF_DEFAULT: "65535"
      CONFIG_TCP_WND_DEFAULT: "512000"
      CONFIG_TCP_RECVMBOX_SIZE: "64"
   
psram:
  mode: quad  # quad for N8R2 and octal for N16R8
  speed: 80MHz

# Enable logging
logger:
  hardware_uart: UART0
  level: INFO

# Enable Home Assistant API
api:
  on_client_connected:
    then:
      - delay: 50ms
      - light.turn_off: light_id
      - if:
          condition:
            switch.is_off: mute
          then:
            - micro_wake_word.start:
  on_client_disconnected:
    then:
      - voice_assistant.stop: 

ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: NONE
  ap:
    ssid: "Voice Assistant 1 AP"
    password: "12345678"

captive_portal:
web_server:
improv_serial:

# ========== SENSORS ==========

sensor:
  - platform: wifi_signal
    name: "WiFi Signal (dBm)"
    id: wifi_signal_db
    update_interval: 60s
    entity_category: "diagnostic"

  - platform: uptime
    name: "Uptime"
    unit_of_measurement: "s"
    entity_category: "diagnostic"

text_sensor:
  - platform: wifi_info
    ssid:
      name: "Connected SSID"
      icon: "mdi:wifi"
      entity_category: "diagnostic"

# ========== SWITCH (MUTE) ==========
switch:
  - platform: template
    id: mute
    name: Mute
    optimistic: true
    restore_mode: RESTORE_DEFAULT_OFF
    on_turn_on: 
      - micro_wake_word.stop:
      - voice_assistant.stop:
      - light.turn_on:
          id: light_id           
          red: 100%
          green: 0%
          blue: 0%
          brightness: 60%
          effect: fast pulse 
      - delay: 2s
      - light.turn_on:
          id: light_id           
          red: 100%
          green: 0%
          blue: 0%
          brightness: 30%
          effect: none
    on_turn_off:
      - light.turn_on:
          id: light_id           
          red: 0%
          green: 100%
          blue: 0%
          brightness: 60%
          effect: fast pulse 
      - delay: 2s
      - light.turn_off: light_id
      - micro_wake_word.start:
   
# ========== LIGHT ==========
light:
  - platform: esp32_rmt_led_strip
    id: light_id
    rgb_order: GRB
    pin: GPIO21
    num_leds: 1
    chipset: ws2812
    name: "Light"
    effects:
      - pulse:
      - pulse:
          name: "Fast Pulse"
          transition_length: 0.5s
          update_interval: 0.5s
          min_brightness: 0%
          max_brightness: 100%
          
          
# ========== AUDIO HARDWARE ==========       
i2s_audio:
  - id: i2s_audio_mic_id
    i2s_lrclk_pin: GPIO3  #WS 
    i2s_bclk_pin: GPIO2   #SCK
  - id: i2s_audio_speaker_id
    i2s_lrclk_pin: GPIO6  #LRC 
    i2s_bclk_pin: GPIO7   #BLCK

microphone:
  - platform: i2s_audio
    id: microphone_id
    adc_type: external
    i2s_din_pin: GPIO4    #SD pin on the INMP441
    i2s_audio_id: i2s_audio_mic_id
    sample_rate: 16000
    channel: left
    
speaker:
  # Hardware Speaker (Physical)
  - platform: i2s_audio
    id: speaker_id
    dac_type: external
    i2s_dout_pin: GPIO8   #DIN Pin of the MAX98357A
    i2s_audio_id: i2s_audio_speaker_id
    sample_rate: 48000

  # Mixer (Virtual: Combines Voice + Music)
  - platform: mixer
    id: audio_mixer
    output_speaker: speaker_id
    source_speakers: 
      - id: announcement_spk_mixer_input # Voice Assistant uses this
      - id: media_spk_mixer_input        # Media Player uses this
        
  # Resampler (Virtual: Adapts Music to 48kHz)
  - platform: resampler
    id: media_spk_resampling_input
    output_speaker: media_spk_mixer_input
    sample_rate: 48000

# ========== MEDIA PLAYER ==========
media_player:
  - platform: speaker
    name: "Media Player"
    id: media_player_id
    # Use the resampling input for media pipeline
    media_pipeline: 
      speaker: media_spk_resampling_input
      num_channels: 1
      format: FLAC
      sample_rate: 48000
    # Use the mixer input directly for announcements
    announcement_pipeline: 
      speaker: announcement_spk_mixer_input
      num_channels: 1
      format: FLAC
      sample_rate: 48000

# ========== WAKE WORD ==========
micro_wake_word:
  on_wake_word_detected:
    then:
      # Duck media audio when wake word is detected
      - if:
          condition:
            media_player.is_playing:
          then:
            - mixer_speaker.apply_ducking:
                id: media_spk_mixer_input
                decibel_reduction: 20
                duration: 0.5s
      # Start Assistant
      - voice_assistant.start:
          wake_word: !lambda return wake_word;
      # LED Feedback
      - light.turn_on:
          id: light_id           
          red: 30%
          green: 30%
          blue: 70%
          brightness: 60%
          effect: fast pulse 
  models:
    - model: hey_jarvis

# ========== VOICE ASSISTANT ==========
voice_assistant:
  id: voice_assistant_id
  microphone: microphone_id
  noise_suppression_level: 2
  auto_gain: 31dBFS
  speaker: announcement_spk_mixer_input
  
  on_listening:
    then:
      - light.turn_on:
          id: light_id
          red: 30%
          green: 30%
          blue: 70%
          brightness: 60%
          effect: fast pulse
          
  on_stt_vad_end:
    then:
      - light.turn_on:
          id: light_id
          red: 70%
          green: 30%
          blue: 70%
          brightness: 60%
          effect: pulse
          
  on_tts_start:
    then:
      - light.turn_on:
          id: light_id
          red: 0%
          green: 100%
          blue: 0%
          brightness: 60%
          effect: none
          
  on_tts_end:
    then:
      - light.turn_off: light_id
      
  on_error:
    then:
      - light.turn_on:
          id: light_id
          red: 100%
          green: 0%
          blue: 0%
          brightness: 100%
          effect: none
      - delay: 1s
      - light.turn_off: light_id
      - if:
          condition:
            switch.is_off: mute
          then:
            - micro_wake_word.start:
            
  on_end:
    then:
      - light.turn_off: light_id
      # Restore media volume after voice assistant finishes
      - mixer_speaker.apply_ducking:
          id: media_spk_mixer_input
          decibel_reduction: 0
          duration: 1.0s
      - wait_until:
          not:
            voice_assistant.is_running:
      - if:
          condition:
            switch.is_off: mute
          then:
            - micro_wake_word.start:
            
  on_idle:
    then:
      - light.turn_off: light_id