esphome:
  name: wardrobe
  friendly_name: "Wardrobe"

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf
    
bluetooth_proxy:
  active: true
  
logger:
api:
ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: NONE # Critical for LED stability
  reboot_timeout: 
    minutes: 2
  ap:
    ssid: "Wardrobe Fallback Hotspot"
    password: "12345678"

captive_portal:
web_server:
improv_serial:
debug:

# ========== INPUTS ==========
number:
  - platform: template
    name: "Effect Speed" 
    id: effect_speed
    optimistic: true
    min_value: 0
    max_value: 100
    step: 1
    initial_value: 10
    entity_category: "config"

# ========== SENSORS ==========
sensor:
  - platform: wifi_signal
    name: "WiFi Signal (dBm)"
    id: wifi_signal_db
    update_interval: 60s
    entity_category: "diagnostic"

  - platform: copy # Reports the WiFi signal strength in %
    source_id: wifi_signal_db
    name: "WiFi Signal"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "%"
    entity_category: "diagnostic"
    device_class: ""

  - platform: uptime
    name: "Uptime"
    unit_of_measurement: "s"
    entity_category: "diagnostic"
    
  - platform: internal_temperature
    name: "ESP Temperature"
    entity_category: "diagnostic"

  - platform: debug
    free:
      name: "Heap Free"

# ========== TEXT SENSORS ==========
text_sensor:
  - platform: wifi_info
    ssid:
      name: "Connected SSID"
      icon: "mdi:wifi"
      entity_category: "diagnostic"
    

# ========== LIGHT ==========

light:
  - platform: esp32_rmt_led_strip
    rgb_order: GRB
    pin: GPIO02
    num_leds: 18
    chipset: WS2812
    id: strip_light
    name: "Light"
    restore_mode: RESTORE_DEFAULT_OFF
    effects: 
      - addressable_rainbow:
      - addressable_twinkle:
      - !include strip_effects/gradient.yaml
      - !include strip_effects/lightning.yaml

  # 2. LOGICAL PARTITIONS
  - platform: partition
    name: "Bottom"
    id: light_bot
    segments: 
      - id: strip_light
        from: 0
        to: 5
        
  - platform: partition
    name: "Middle"
    id: light_mid
    segments: 
      - id: strip_light
        from: 6
        to: 11
        
  - platform: partition
    name: "Top"
    id: light_top
    segments: 
      - id: strip_light
        from: 12
        to: 17
