esphome:
  name: wardrobe
  friendly_name: "Wardrobe"

esp8266:
  board: nodemcuv2
  restore_from_flash: true

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: NONE
  reboot_timeout: 
    minutes: 2
  ap:
    ssid: "Wardrobe AP"
    password: "12345678"

logger:
  level: INFO
api:
ota:
  - platform: esphome
captive_portal:
web_server:
improv_serial:
debug:

# ========== SENSORS ==========
sensor:
  - platform: wifi_signal
    name: "WiFi Signal (dBm)"
    id: wifi_signal_db
    update_interval: 60s
    entity_category: "diagnostic"

  - platform: uptime
    name: "Uptime"
    unit_of_measurement: "s"
    entity_category: "diagnostic"

  - platform: debug
    free:
      name: "Heap Free"

# ========== TEXT SENSORS ==========
text_sensor:
  - platform: wifi_info
    ssid:
      name: "Connected SSID"
      icon: "mdi:wifi"
      entity_category: "diagnostic"
    

# ========== LIGHT ==========

light:
  - platform: neopixelbus
    type: GRB
    variant: WS2812X
    pin: GPIO02
    num_leds: 18
    id: strip_light
    name: "Light"
    restore_mode: RESTORE_DEFAULT_OFF
    effects:
      - addressable_twinkle:
      - random
      - addressable_rainbow
      - addressable_color_wipe
