external_components:
  - source:
      type: git
      url: https://github.com/KaufHA/common
    components: [ ddp ]
    refresh: always

esphome:
  name: cerebro
  friendly_name: "Cerebro"

esp8266:
  board: nodemcuv2
  restore_from_flash: true
  early_pin_init: false

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  min_auth_mode: WPA2
  power_save_mode: NONE
  ap:
    ssid: "Cerebro"
    password: "12345678"

logger:
  level: INFO
api:
ota:
captive_portal:
web_server:
ddp:
debug:

# ========== SENSORS ==========
sensor:
  - platform: wifi_signal
    name: "WiFi Signal (dBm)"
    id: wifi_signal_db
    update_interval: 60s
    entity_category: "diagnostic"

  - platform: uptime
    name: "Uptime"
    unit_of_measurement: "s"
    entity_category: "diagnostic"

  - platform: debug
    free:
      name: "Heap Free"

text_sensor:
  - platform: wifi_info
    ssid:
      name: "Connected SSID"
      icon: "mdi:wifi"
      entity_category: "diagnostic"

# ========== LIGHT ==========
light:
  - platform: neopixelbus
    id: light_id
    type: GRB
    pin: GPIO2
    num_leds: 22
    variant: ws2812x
    name: "Light"
    restore_mode: RESTORE_DEFAULT_OFF
    effects:
      - random:
      - addressable_ddp:
          name: DDP
          timeout: 2s